//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Luong
    {
        public string MaNhanVien { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
        public Nullable<decimal> KhauTruThue { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
