//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string MaNhanVien { get; set; }
        public string ThangNam { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public Nullable<int> LuongThucLanh { get; set; }
    
        public string TenNhanVien { get; set; }
        public virtual NhanVien NhanVien { get; set; }

        public List<Luong> getList()
        {
            throw new NotImplementedException();
        }
    }
}
